# Generated by Django 4.2.7 on 2023-12-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=80)),
                ('valor_aluguel', models.FloatField()),
                ('data_vencimento_aluguel', models.DateField()),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino')),
            ],
        ),
    ]
