# Generated by Django 4.2.7 on 2024-01-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=80)),
                ('valor_aluguel', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('data_ultimo_pagamento', models.DateField()),
                ('data_vencimento_aluguel', models.DateField()),
                ('adiantamento', models.JSONField(blank=True, default={'dia_do_adiantamento': '00/00/0000', 'valor_do_adiantamento': 0.0}, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identificador_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.casa')),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino'),
        ),
    ]
