# Generated by Django 4.2.9 on 2024-01-22 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despesas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=80)),
                ('valor_aluguel', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('data_ultimo_pagamento', models.DateField(verbose_name='data_ultimo_pagamento')),
                ('data_vencimento_aluguel', models.DateField(verbose_name='data_vencimento_aluguel')),
                ('despesa', models.ManyToManyField(to='despesas.despesas')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=10, unique=True, verbose_name='RG')),
                ('profissao', models.CharField(max_length=40, verbose_name='Profissão')),
                ('estado_civil', models.CharField(max_length=20, verbose_name='Estado civil')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('despesa', models.ManyToManyField(to='despesas.despesas')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identificador_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.casa')),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino'),
        ),
    ]
