# Generated by Django 4.2.7 on 2023-12-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='identicador',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
