# Generated by Django 4.2.9 on 2024-02-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
        ('gestaoAluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('paga_inteira', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='casa',
            name='despesa',
            field=models.ManyToManyField(blank=True, to='despesas.despesas'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='representante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='despesa',
            field=models.ManyToManyField(blank=True, to='despesas.despesas'),
        ),
        migrations.AddField(
            model_name='casa',
            name='morador',
            field=models.ManyToManyField(blank=True, to='gestaoAluguel.morador'),
        ),
    ]
