# Generated by Django 4.2.7 on 2024-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_remove_despesas_casa_remove_despesas_inquilino'),
        ('gestaoAluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='despesa',
            field=models.ManyToManyField(blank=True, null=True, to='despesas.despesas'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='despesa',
            field=models.ManyToManyField(blank=True, null=True, to='despesas.despesas'),
        ),
    ]
