# Generated by Django 4.2.7 on 2024-01-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0002_casa_despesa_inquilino_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='endereco',
            field=models.CharField(default=1, max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquilino',
            name='profissao',
            field=models.CharField(default=1, max_length=40, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquilino',
            name='rg',
            field=models.CharField(default=1, max_length=25, unique=True, verbose_name='Rg'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_de_locacao', models.IntegerField()),
                ('tipo_de_locação', models.CharField(default='residencial', max_length=15)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino')),
            ],
        ),
    ]
