# Generated by Django 4.2.7 on 2024-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_remove_despesas_casa_remove_despesas_inquilino'),
        ('gestaoAluguel', '0003_inquilino_endereco_inquilino_profissao_inquilino_rg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='casa',
            name='despesa',
            field=models.ManyToManyField(to='despesas.despesas'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='despesa',
            field=models.ManyToManyField(to='despesas.despesas'),
        ),
    ]
