# Generated by Django 4.2.7 on 2024-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0004_remove_inquilino_endereco_alter_casa_despesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='estado_civil',
            field=models.CharField(default=1, max_length=20, verbose_name='Estado civil'),
            preserve_default=False,
        ),
    ]
