# Generated by Django 4.2.7 on 2023-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0004_alter_casa_adiantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='adiantamento',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
