# Generated by Django 4.2.7 on 2024-01-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0005_inquilino_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesRendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_mes', models.CharField(max_length=15)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
