# Generated by Django 4.2.7 on 2024-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0006_mesrendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='inquilino',
        ),
        migrations.DeleteModel(
            name='MesRendimento',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
