# Generated by Django 4.2.7 on 2024-01-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0008_alter_casa_data_ultimo_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='adiantamento',
        ),
    ]
