# Generated by Django 4.2.7 on 2024-01-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestaoAluguel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Água'), ('E', 'Energia'), ('I', 'Internet'), ('M', 'Máquina')], max_length=1)),
                ('data_chegada', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('qtd_pessoas', models.IntegerField()),
                ('valor', models.FloatField()),
                ('valor_por_pessoa', models.FloatField(blank=True, null=True)),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.casa')),
                ('inquilino', models.ManyToManyField(to='gestaoAluguel.inquilino')),
            ],
        ),
    ]
