# Generated by Django 4.2.9 on 2024-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Água'), ('E', 'Energia'), ('I', 'Internet'), ('M', 'Máquina')], max_length=1)),
                ('nome_despesa', models.CharField(max_length=50)),
                ('data_chegada', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('qtd_pessoas', models.IntegerField()),
                ('valor', models.FloatField()),
                ('valor_por_pessoa', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
