# Generated by Django 4.2.7 on 2023-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data_chegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='valor_por_pessoa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
