# Generated by Django 4.2.7 on 2024-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0001_initial'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='casa',
        ),
        migrations.AddField(
            model_name='despesas',
            name='casa',
            field=models.ManyToManyField(to='gestaoAluguel.casa'),
        ),
    ]
