# Generated by Django 4.2.9 on 2024-02-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0002_morador_alter_casa_despesa_alter_casa_representante_and_more'),
        ('despesas', '0003_rename_despesas_despesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='nome_despesa',
        ),
        migrations.AddField(
            model_name='despesa',
            name='casa',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='gestaoAluguel.casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='morador',
            field=models.ManyToManyField(blank=True, related_name='morador', to='gestaoAluguel.morador'),
        ),
    ]
