# Generated by Django 4.2.7 on 2024-01-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesas_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesas',
            old_name='identificador',
            new_name='nome_despesa',
        ),
    ]
