# Generated by Django 4.2.7 on 2024-01-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoAluguel', '0001_initial'),
        ('despesas', '0004_rename_identificador_despesas_nome_despesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='despesas',
            name='inquilino',
        ),
        migrations.AddField(
            model_name='despesas',
            name='casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesas',
            name='inquilino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestaoAluguel.inquilino'),
            preserve_default=False,
        ),
    ]
