# Generated by Django 4.2.9 on 2024-02-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_remove_despesa_nome_despesa_despesa_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='qtd_pessoas',
        ),
    ]
