# Generated by Django 4.2.7 on 2024-01-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_remove_despesas_casa_remove_despesas_inquilino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='despesas',
            name='inquilino',
        ),
    ]
